"use client";
import Link from "next/link"; import { useState } from "react";
export type SystematicRow = { rank: number; ticker: string; company: string; sector: string; industry: string; watchlist: boolean; alpha: number | null; quality: number | null; value: number | null; growth: number | null; momentum: number | null; confidence: number | null; risk: number | null; liquidity: number | null; industryPercentile: number | null; universePercentile: number | null; band: string; calculatedAt: string; dataAsOf: string; priceAsOf: string | null; warnings: unknown; contributions: unknown; analysis: null | { summary: string; generatedAt: string; dataAsOf: string; stale: boolean } };
type SortKey = "alpha" | "quality" | "value" | "growth" | "momentum" | "confidence" | "risk" | "liquidity";
const shown = (value: number | null) => value == null ? "—" : value.toFixed(1);
export function SystematicRankingTable({ initialRows }: { initialRows: SystematicRow[] }) {
  const [query, setQuery] = useState(""); const [sector, setSector] = useState(""); const [industry, setIndustry] = useState(""); const [minimumAlpha, setMinimumAlpha] = useState(0); const [minimumConfidence, setMinimumConfidence] = useState(0); const [band, setBand] = useState(""); const [watchlist, setWatchlist] = useState(false); const [sort, setSort] = useState<SortKey>("alpha"); const [descending, setDescending] = useState(true);
  const sectors = [...new Set(initialRows.map((row) => row.sector))].sort(); const industries = [...new Set(initialRows.filter((row) => !sector || row.sector === sector).map((row) => row.industry))].sort();
  const rows = initialRows.filter((row) => `${row.ticker} ${row.company}`.toLowerCase().includes(query.toLowerCase()) && (!sector || row.sector === sector) && (!industry || row.industry === industry) && (row.alpha ?? -1) >= minimumAlpha && (row.confidence ?? -1) >= minimumConfidence && (!band || row.band === band) && (!watchlist || row.watchlist)).sort((a, b) => ((b[sort] ?? -1) - (a[sort] ?? -1)) * (descending ? 1 : -1) || a.ticker.localeCompare(b.ticker)).map((row, index) => ({ ...row, rank: index + 1 }));
  const chooseSort = (key: SortKey) => { if (key === sort) setDescending((value) => !value); else { setSort(key); setDescending(true); } };
  const restore = () => { setSort("alpha"); setDescending(true); };
  return <section className="space-y-3"><div className="panel grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-7"><label className="text-xs">Search<input className="mt-1 w-full rounded border border-[var(--border)] bg-transparent px-2 py-1.5" value={query} onChange={(event) => setQuery(event.target.value)} /></label><label className="text-xs">Sector<select className="mt-1 w-full rounded border border-[var(--border)] bg-[var(--panel)] px-2 py-1.5" value={sector} onChange={(event) => { setSector(event.target.value); setIndustry(""); }}><option value="">All</option>{sectors.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-xs">Industry<select className="mt-1 w-full rounded border border-[var(--border)] bg-[var(--panel)] px-2 py-1.5" value={industry} onChange={(event) => setIndustry(event.target.value)}><option value="">All</option>{industries.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-xs">Minimum alpha<input type="number" min="0" max="100" className="mt-1 w-full rounded border border-[var(--border)] bg-transparent px-2 py-1.5" value={minimumAlpha} onChange={(event) => setMinimumAlpha(Number(event.target.value))} /></label><label className="text-xs">Minimum confidence<input type="number" min="0" max="100" className="mt-1 w-full rounded border border-[var(--border)] bg-transparent px-2 py-1.5" value={minimumConfidence} onChange={(event) => setMinimumConfidence(Number(event.target.value))} /></label><label className="text-xs">Candidate band<select className="mt-1 w-full rounded border border-[var(--border)] bg-[var(--panel)] px-2 py-1.5" value={band} onChange={(event) => setBand(event.target.value)}><option value="">All</option>{["CANDIDATE","HOLD_RANGE","NEUTRAL","EXIT_RANGE","INSUFFICIENT_DATA"].map((item) => <option key={item}>{item.replaceAll("_", " ")}</option>)}</select></label><label className="flex items-end gap-2 pb-1 text-xs"><input type="checkbox" checked={watchlist} onChange={(event) => setWatchlist(event.target.checked)} /> Watchlist only</label></div>
    <div className="flex justify-between text-sm muted"><span>{rows.length} visible securities. Rankings are research classifications, not recommendations.</span><button className="rounded border border-[var(--border)] px-3 py-1" onClick={restore}>Restore model ranking</button></div>
    <div className="panel overflow-x-auto"><table className="w-full min-w-[1450px] text-left text-xs"><thead><tr className="border-b border-[var(--border)]">{["Rank","Ticker","Company"].map((label) => <th className="p-2" key={label}>{label}</th>)}{(["alpha","quality","value","growth","momentum","confidence","risk","liquidity"] as SortKey[]).map((key) => <th className="p-2" key={key}><button onClick={() => chooseSort(key)}>{key[0].toUpperCase()+key.slice(1)}{sort === key ? descending ? " ↓" : " ↑" : ""}</button></th>)}<th className="p-2">Industry %ile</th><th className="p-2">Signal / changes</th><th className="p-2">Analysis</th></tr></thead><tbody>{rows.map((row) => <tr className="border-b border-[var(--border)] align-top" key={row.ticker}><td className="p-2 font-semibold">{row.rank}</td><td className="p-2"><Link className="font-bold text-[var(--accent)]" href={`/stocks/${row.ticker}`}>{row.ticker}</Link><span className="mt-1 block muted">{row.band.replaceAll("_", " ")}</span></td><td className="p-2"><span className="font-medium">{row.company}</span><span className="block muted">{row.industry}</span></td><td className="p-2 text-base font-bold">{shown(row.alpha)}</td>{[row.quality,row.value,row.growth,row.momentum,row.confidence,row.risk,row.liquidity].map((value, index) => <td className="p-2" key={index}>{shown(value)}</td>)}<td className="p-2">{row.industryPercentile == null ? "—" : `${(row.industryPercentile * 100).toFixed(0)}%`}</td><td className="p-2"><span>1D: — · 30D: —</span><span className="block muted">Score {row.calculatedAt}</span><span className="block muted">Price {row.priceAsOf ?? "—"}</span>{Array.isArray(row.warnings) && row.warnings.length > 0 && <span className="block warning">Data warnings</span>}</td><td className="max-w-64 p-2">{row.analysis ? <><span>{row.analysis.summary}</span><span className="block muted">{row.analysis.generatedAt} · {row.analysis.stale ? "Stale" : "Current"}</span></> : <span className="muted">Not analyzed</span>}</td></tr>)}</tbody></table>{!rows.length && <p className="p-10 text-center muted">No real factor snapshots match these filters.</p>}</div></section>;
}
