import { notFound } from "next/navigation"; import { StoredPriceChart } from "@/components/charts/stored-price-chart"; import { databaseConfigured } from "@/lib/database/prisma"; import { stockResearch } from "@/lib/database/research"; import { tickerSchema } from "@/lib/validation/watchlist";
const number = (value: { toNumber(): number } | null | undefined) => value?.toNumber() ?? null; const shown = (value: { toNumber(): number } | null | undefined) => value == null ? "—" : value.toNumber().toFixed(1);
export default async function StockPage({ params }: { params: Promise<{ ticker: string }> }) {
  const parsed = tickerSchema.safeParse((await params).ticker); if (!parsed.success || !databaseConfigured()) notFound(); const company = await stockResearch(parsed.data); if (!company) notFound();
  const score = company.factorScores[0]; const prior = company.factorScores[1]; const oldest = company.factorScores.at(-1); const latestPrice = company.priceBars[0]; const model = score?.modelVersion;
  const prices = company.priceBars.slice().reverse().map((bar) => ({ timestamp: bar.timestamp.toISOString(), raw: number(bar.adjustedClose ?? bar.close)! })); const base = prices[0]?.raw; const chart = prices.map((point) => ({ ...point, relative: base ? point.raw / base * 100 : null }));
  const rawByKey = new Map(company.featureSnapshots.map((item) => [item.featureKey, item])); const contributions = company.normalizedFeatures.filter((item, index, all) => all.findIndex((other) => other.featureKey === item.featureKey) === index);
  return <main className="mx-auto max-w-[1450px] space-y-7 px-4 py-8 sm:px-6"><div role="status" className={`rounded-xl border p-4 text-sm ${score ? "border-emerald-500/40 bg-emerald-500/10" : "border-amber-500/40 bg-amber-500/10"}`}><strong>{score ? "Stored real-data research" : "Insufficient data"}.</strong> {score ? `Model ${model?.modelKey} ${model?.version}; calculated ${score.calculatedAt.toISOString()}.` : "No non-mock factor snapshot exists for this security."}</div>
    <header><p className="text-sm font-semibold text-[var(--accent)]">{company.exchange ?? "Exchange unavailable"} · {company.sector} · {company.industry}</p><h1 className="mt-1 text-3xl font-bold">{company.name} <span className="muted">({company.ticker})</span></h1><dl className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Latest price", latestPrice ? `$${number(latestPrice.adjustedClose ?? latestPrice.close)?.toFixed(2)}` : "—"],["Price timestamp",latestPrice?.timestamp.toISOString() ?? "—"],["Universe eligibility",company.universeMemberships.length ? "Eligible" : "Ineligible"],["Model band",score?.candidateBand.replaceAll("_"," ") ?? "Insufficient data"],["Market capitalization","Unavailable"]].map(([label,value]) => <div className="panel p-3" key={label}><dt className="text-xs muted">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl></header>
    <section className="panel p-5"><h2 className="text-xl font-bold">Performance</h2><p className="mb-4 text-sm muted">Adjusted observations; select normalized or raw price. SPY, QQQ, and sector lines appear only after their stored bars are joined—no interpolation or fabricated benchmarks.</p><StoredPriceChart data={chart} /></section>
    <section><h2 className="text-xl font-bold">Factor profile</h2><dl className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[["Alpha",shown(score?.alphaScore)],["Quality",shown(score?.qualityScore)],["Value",shown(score?.valueScore)],["Growth",shown(score?.growthScore)],["Momentum",shown(score?.momentumScore)],["Confidence",shown(score?.confidenceScore)],["Risk",shown(score?.riskScore)],["Liquidity",shown(score?.liquidityScore)],["1D alpha change",score && prior ? (number(score.alphaScore)!-number(prior.alphaScore)!).toFixed(1) : "—"],["30D alpha change",score && oldest ? (number(score.alphaScore)!-number(oldest.alphaScore)!).toFixed(1) : "—"],["Industry percentile",score?.industryPercentile ? `${(number(score.industryPercentile)!*100).toFixed(0)}%` : "—"],["Universe percentile",score?.universePercentile ? `${(number(score.universePercentile)!*100).toFixed(0)}%` : "—"]].map(([label,value]) => <div className="panel p-3" key={label}><dt className="text-xs muted">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl></section>
    <section className="panel overflow-x-auto p-5"><h2 className="text-xl font-bold">Feature contributions</h2><table className="mt-4 w-full min-w-[850px] text-left text-sm"><thead><tr className="border-b border-[var(--border)]">{["Feature","Raw value","Peer percentile","Direction","Weight","Contribution","Data as of"].map((item)=><th className="p-2" key={item}>{item}</th>)}</tr></thead><tbody>{contributions.map((item) => { const raw=rawByKey.get(item.featureKey); return <tr className="border-b border-[var(--border)]" key={item.featureKey}><td className="p-2 font-medium">{item.featureKey}</td><td className="p-2">{raw?.value?.toString() ?? "Missing"}</td><td className="p-2">{(number(item.percentileRank)!*100).toFixed(1)}%</td><td className="p-2">{item.direction.replaceAll("_"," ")}</td><td className="p-2">See model configuration</td><td className="p-2">Stored in score audit JSON</td><td className="p-2">{raw?.sourceAsOf?.toISOString() ?? item.asOfDate.toISOString()}</td></tr>; })}</tbody></table>{!contributions.length && <p className="mt-4 muted">No calculated features are available.</p>}</section>
    <section className="grid gap-5 lg:grid-cols-2"><div className="panel p-5"><h2 className="text-xl font-bold">Factor history</h2><ul className="mt-3 space-y-2 text-sm">{company.factorScores.map((item)=><li className="flex justify-between" key={item.id}><span>{item.asOfDate.toISOString().slice(0,10)}</span><span>Alpha {shown(item.alphaScore)} · Confidence {shown(item.confidenceScore)}</span></li>)}</ul>{!company.factorScores.length && <p className="mt-3 muted">History begins only when the factor engine produces real snapshots.</p>}</div><div className="panel p-5"><h2 className="text-xl font-bold">Peer comparison</h2><p className="mt-3 text-sm muted">Peer statistics are stored per feature. Latest normalized inputs used {contributions[0]?.peerGroupType?.toLowerCase() ?? "no"} peers; no cross-industry comparison is fabricated.</p></div></section>
    <section className="panel p-5"><h2 className="text-xl font-bold">Data audit</h2><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4">{[["Price provider",latestPrice?.provider ?? "Unavailable"],["Fundamentals provider",company.filings[0]?.provider ?? "Unavailable"],["Latest filing",company.filings[0]?.accessionNumber ?? "Unavailable"],["Financial period",company.filings[0]?.periodEnd?.toISOString() ?? "Unavailable"],["Retrieved at",latestPrice?.retrievedAt.toISOString() ?? "Unavailable"],["Effective at",latestPrice?.effectiveAt?.toISOString() ?? "Unavailable"],["Score calculated",score?.calculatedAt.toISOString() ?? "Unavailable"],["Model / universe rules",score ? `${model?.modelKey} ${model?.version} / ${score.universeRuleVersion}` : "Unavailable"],["Analysis",company.analyses[0] ? `${company.analyses[0].generatedAt.toISOString()} (${company.analyses[0].dataAsOf.toISOString()} data)` : "Not analyzed"]].map(([label,value])=><div key={label}><dt className="muted">{label}</dt><dd>{value}</dd></div>)}</dl></section>
  </main>;
}
