import { Prisma } from "@prisma/client";
import { prisma } from "../database/prisma";
import { DEFAULT_UNIVERSE_RULES, MODEL_V0 } from "./config";
import { FEATURE_REGISTRY, isApplicable, momentumFeatures, ratio, safeCagr, safeEpsGrowth, safeGrowth } from "./features";
import { normalizeCrossSection } from "./normalization";
import { aggregateAlpha, candidateBand, confidenceScore, scoreFactor, type Contribution } from "./factor-model";
import { calculateRisk, riskClassification, riskScoreFromMetrics, type Ohlcv } from "./risk";
import { calculateLiquidity } from "./liquidity";

const number = (value: Prisma.Decimal | bigint | null | undefined) => value == null ? null : Number(value);
type Calc = { value: number | null; nullReason?: string; warnings?: string[]; sourceAsOf?: Date; sourceAvailableAt?: Date; provider?: string };
export type ResearchFact = { metricKey: string; value: Prisma.Decimal; periodStart: Date | null; periodEnd: Date; periodType: string; publishedAt: Date; retrievedAt: Date; provider: string; isRestated: boolean };

const durationMetrics = new Set(["revenue", "gross_profit", "operating_income", "net_income", "operating_cash_flow", "capital_expenditure", "interest_expense", "diluted_shares", "diluted_eps"]);
const instantMetrics = new Set(["assets", "stockholders_equity", "common_equity", "cash", "debt", "debt_current"]);

export function comparableSeries(facts: ResearchFact[], key: string) {
  const candidates = facts.filter((fact) => fact.metricKey === key && (durationMetrics.has(key) ? fact.periodType === "ANNUAL" : instantMetrics.has(key) ? fact.periodType === "INSTANT" : true));
  const byPeriod = new Map<number, ResearchFact>();
  for (const fact of candidates) {
    const period = fact.periodEnd.getTime(); const existing = byPeriod.get(period);
    if (!existing || fact.publishedAt > existing.publishedAt || (fact.publishedAt.getTime() === existing.publishedAt.getTime() && fact.retrievedAt > existing.retrievedAt)) byPeriod.set(period, fact);
  }
  return [...byPeriod.values()].sort((a, b) => b.periodEnd.getTime() - a.periodEnd.getTime());
}

const deviation = (values: number[]) => { if (values.length < 2) return null; const mean = values.reduce((a, b) => a + b, 0) / values.length; return Math.sqrt(values.reduce((sum, value) => sum + (value - mean) ** 2, 0) / (values.length - 1)); };

export function buildFundamentalFeatures(facts: ResearchFact[], marketCap: number | null): Record<string, Calc> {
  const value = (key: string, index = 0) => number(comparableSeries(facts, key)[index]?.value);
  const source = (key: string) => comparableSeries(facts, key)[0];
  const sumNullable = (...values: Array<number | null>) => values.every((item) => item == null) ? null : values.reduce<number>((sum, item) => sum + (item ?? 0), 0);
  const revenue = value("revenue"), gross = value("gross_profit"), operatingIncome = value("operating_income"), netIncome = value("net_income"), operatingCashFlow = value("operating_cash_flow"), capex = value("capital_expenditure");
  const assets = value("assets"), priorAssets = value("assets", 1), averageAssets = assets == null || priorAssets == null ? null : (assets + priorAssets) / 2;
  const equity = value("stockholders_equity") ?? value("common_equity"), priorEquity = value("stockholders_equity", 1) ?? value("common_equity", 1), averageEquity = equity == null || priorEquity == null ? null : (equity + priorEquity) / 2;
  const cash = value("cash"), debt = sumNullable(value("debt"), value("debt_current")), interest = value("interest_expense"), shares = value("diluted_shares"), eps = value("diluted_eps");
  const freeCashFlow = operatingCashFlow == null || capex == null ? null : operatingCashFlow - Math.abs(capex);
  const enterpriseValue = marketCap == null || debt == null ? null : marketCap + debt - (cash ?? 0);
  const base = (calculated: number | null, key = "revenue"): Calc => { const fact = source(key); const available = fact ? new Date(Math.max(fact.publishedAt.getTime(), fact.retrievedAt.getTime())) : undefined; return { value: calculated, sourceAsOf: fact?.periodEnd, sourceAvailableAt: available, provider: fact?.provider, nullReason: calculated == null ? "MISSING_OR_INVALID_INPUT" : undefined, warnings: fact?.isRestated ? ["RESTATED_SOURCE_FACT"] : undefined }; };
  const margins = (numerator: string) => comparableSeries(facts, numerator).slice(0, 3).map((fact) => ratio(number(fact.value), number(comparableSeries(facts, "revenue").find((item) => item.periodEnd.getTime() === fact.periodEnd.getTime())?.value))).filter((item): item is number => item != null);
  const revenueGrowth = [safeGrowth(revenue, value("revenue", 1)), safeGrowth(value("revenue", 1), value("revenue", 2))];
  const epsGrowth = [safeEpsGrowth(eps, value("diluted_eps", 1)), safeEpsGrowth(value("diluted_eps", 1), value("diluted_eps", 2))];
  const priorFcf = value("operating_cash_flow", 1) == null || value("capital_expenditure", 1) == null ? null : value("operating_cash_flow", 1)! - Math.abs(value("capital_expenditure", 1)!);
  const operatingMargins = margins("operating_income");
  return {
    gross_margin: base(ratio(gross, revenue)), operating_margin: base(ratio(operatingIncome, revenue)), net_margin: base(ratio(netIncome, revenue)), fcf_margin: base(ratio(freeCashFlow, revenue)),
    roa: base(ratio(netIncome, averageAssets)), roe: base(ratio(netIncome, averageEquity)), roic_approx: base(operatingIncome == null || debt == null || equity == null ? null : ratio(operatingIncome * .79, debt + equity - (cash ?? 0))), gross_profitability: base(ratio(gross, averageAssets)),
    ocf_to_net_income: base(ratio(operatingCashFlow, netIncome)), fcf_to_net_income: base(ratio(freeCashFlow, netIncome)), accruals_ratio: base(ratio(netIncome == null || operatingCashFlow == null ? null : netIncome - operatingCashFlow, averageAssets)),
    net_debt_to_ebitda: base(null), debt_to_equity: base(ratio(debt, equity)), interest_coverage: base(interest != null && interest > 0 ? ratio(operatingIncome, interest) : null),
    operating_margin_stability_3y: base(deviation(operatingMargins)), earnings_stability_3y: base(deviation(comparableSeries(facts, "net_income").slice(0, 3).map((fact) => number(fact.value)!).filter(Number.isFinite))),
    share_change_1y: base(safeGrowth(shares, value("diluted_shares", 1)), "diluted_shares"), share_change_3y: base(safeCagr(shares, value("diluted_shares", 3), 3), "diluted_shares"),
    revenue_growth_1y: base(revenueGrowth[0]), revenue_cagr_3y: base(safeCagr(revenue, value("revenue", 3), 3)), eps_growth_1y: base(epsGrowth[0], "diluted_eps"), eps_cagr_3y: base(safeCagr(eps, value("diluted_eps", 3), 3), "diluted_eps"),
    fcf_growth_1y: base(safeGrowth(freeCashFlow, priorFcf)), fcf_cagr_3y: base(null), revenue_growth_acceleration: base(revenueGrowth[0] != null && revenueGrowth[1] != null ? revenueGrowth[0] - revenueGrowth[1] : null), eps_growth_acceleration: base(epsGrowth[0] != null && epsGrowth[1] != null ? epsGrowth[0] - epsGrowth[1] : null, "diluted_eps"),
    gross_margin_change: base(null), operating_margin_change: base(operatingMargins.length >= 2 ? operatingMargins[0] - operatingMargins[1] : null), fcf_margin_change: base(null),
    earnings_yield: base(marketCap && netIncome != null && netIncome > 0 ? netIncome / marketCap : null), fcf_yield: base(marketCap && freeCashFlow != null ? freeCashFlow / marketCap : null), ebit_to_ev: base(enterpriseValue && enterpriseValue > 0 && operatingIncome != null ? operatingIncome / enterpriseValue : null), ebitda_to_ev: base(null), sales_to_ev: base(enterpriseValue && enterpriseValue > 0 && revenue != null ? revenue / enterpriseValue : null), book_to_market: base(marketCap && equity != null ? equity / marketCap : null), shareholder_yield: base(null), historical_valuation_percentile: base(null),
  };
}

const toOhlcv = (bars: Array<{ timestamp: Date; open: Prisma.Decimal; high: Prisma.Decimal; low: Prisma.Decimal; close: Prisma.Decimal; adjustedClose: Prisma.Decimal | null; volume: bigint | null }>): Ohlcv[] => bars.map((bar) => ({ timestamp: bar.timestamp, open: number(bar.open)!, high: number(bar.high)!, low: number(bar.low)!, close: number(bar.close)!, adjustedClose: number(bar.adjustedClose ?? bar.close)!, volume: number(bar.volume) }));
async function latestBars(companyId: string, asOf: Date, take = 800) { const bars = await prisma.priceBar.findMany({ where: { companyId, timestamp: { lte: asOf }, retrievedAt: { lte: asOf }, isMock: false, interval: "1d" }, orderBy: { timestamp: "desc" }, take }); return bars.reverse(); }

async function eligibleCompanyIds(asOf: Date, universeId: string) {
  const memberships = await prisma.universeMembership.findMany({ where: { universeId, effectiveFrom: { lte: asOf }, OR: [{ effectiveTo: null }, { effectiveTo: { gt: asOf } }] }, include: { company: true } }); const eligible = new Set<string>();
  for (const { company } of memberships) {
    if (!company.active || !company.country || !DEFAULT_UNIVERSE_RULES.allowedCountries.includes(company.country as "US") || !company.securityType || !DEFAULT_UNIVERSE_RULES.allowedSecurityTypes.includes(company.securityType as "COMMON_STOCK" | "ADR")) continue;
    const [market, bars] = await Promise.all([prisma.marketSnapshot.findFirst({ where: { companyId: company.id, isMock: false, retrievedAt: { lte: asOf }, effectiveAt: { lte: asOf }, provider: { not: "UNKNOWN_LEGACY" } }, orderBy: { effectiveAt: "desc" } }), latestBars(company.id, asOf, DEFAULT_UNIVERSE_RULES.minimumTradingHistoryDays)]);
    const liquidity = calculateLiquidity(toOhlcv(bars));
    if ((number(market?.marketCap) ?? 0) >= DEFAULT_UNIVERSE_RULES.minimumMarketCapUsd && (liquidity.price ?? 0) >= DEFAULT_UNIVERSE_RULES.minimumPriceUsd && liquidity.tradingHistoryDays >= DEFAULT_UNIVERSE_RULES.minimumTradingHistoryDays && (liquidity.medianDollarVolume ?? 0) >= DEFAULT_UNIVERSE_RULES.minimumMedianDailyDollarVolumeUsd) eligible.add(company.id);
  }
  return eligible;
}

export async function calculateFeatures(asOf: Date) {
  const universe = await prisma.investmentUniverse.findFirstOrThrow({ where: { active: true } }); const members = await prisma.universeMembership.findMany({ where: { universeId: universe.id, effectiveFrom: { lte: asOf }, OR: [{ effectiveTo: null }, { effectiveTo: { gt: asOf } }] }, include: { company: true } }); let written = 0; const failures: string[] = [];
  for (const { company } of members) try {
    const [facts, bars, market] = await Promise.all([prisma.financialFact.findMany({ where: { companyId: company.id, publishedAt: { lte: asOf }, retrievedAt: { lte: asOf }, isMock: false, periodEnd: { lte: asOf } } }), latestBars(company.id, asOf), prisma.marketSnapshot.findFirst({ where: { companyId: company.id, isMock: false, retrievedAt: { lte: asOf }, effectiveAt: { lte: asOf }, provider: { not: "UNKNOWN_LEGACY" } }, orderBy: { effectiveAt: "desc" } })]);
    const fundamental = buildFundamentalFeatures(facts, number(market?.marketCap)), ordered = toOhlcv(bars), momentum = momentumFeatures(ordered.map((bar) => bar.adjustedClose), ordered.map((bar) => bar.volume ?? 0));
    for (const definition of FEATURE_REGISTRY.filter((item) => item.factor !== "RISK")) {
      let calculated: Calc = fundamental[definition.key] ?? { value: (momentum as Record<string, number | null>)[definition.key] ?? null, sourceAsOf: bars.at(-1)?.timestamp, sourceAvailableAt: bars.at(-1)?.retrievedAt, provider: bars.at(-1)?.provider };
      if (!isApplicable(definition, company.securityType, company.industry)) calculated = { value: null, nullReason: "NOT_APPLICABLE" }; else if (definition.minimumHistoryDays && bars.length < definition.minimumHistoryDays) calculated = { ...calculated, value: null, nullReason: "INSUFFICIENT_HISTORY", warnings: [`Requires ${definition.minimumHistoryDays} trading observations`] };
      await prisma.featureSnapshot.upsert({ where: { companyId_asOfDate_featureKey_modelVersion: { companyId: company.id, asOfDate: asOf, featureKey: definition.key, modelVersion: MODEL_V0.version } }, update: { value: calculated.value, formulaVersion: definition.formulaVersion, calculatedAt: new Date(), sourceAsOf: calculated.sourceAsOf, sourceAvailableAt: calculated.sourceAvailableAt, provider: calculated.provider, confidence: calculated.value == null ? 0 : 1, nullReason: calculated.nullReason, warnings: calculated.warnings ?? [] }, create: { companyId: company.id, asOfDate: asOf, featureKey: definition.key, value: calculated.value, modelVersion: MODEL_V0.version, formulaVersion: definition.formulaVersion, calculatedAt: new Date(), sourceAsOf: calculated.sourceAsOf, sourceAvailableAt: calculated.sourceAvailableAt, provider: calculated.provider, confidence: calculated.value == null ? 0 : 1, nullReason: calculated.nullReason, warnings: calculated.warnings ?? [] } }); written++;
    }
  } catch (error) { failures.push(`${company.ticker}: ${error instanceof Error ? error.message : String(error)}`); }
  return { universe, members, written, failures };
}

export async function normalizeFeatures(asOf: Date) {
  const universe = await prisma.investmentUniverse.findFirstOrThrow({ where: { active: true } }), eligible = await eligibleCompanyIds(asOf, universe.id); const rows = await prisma.featureSnapshot.findMany({ where: { asOfDate: asOf, modelVersion: MODEL_V0.version, companyId: { in: [...eligible] } }, include: { company: true } }); let written = 0;
  for (const definition of FEATURE_REGISTRY.filter((item) => item.factor !== "RISK")) for (const item of normalizeCrossSection(rows.filter((row) => row.featureKey === definition.key).map((row) => ({ id: row.id, value: number(row.value), industry: row.company.industry, sector: row.company.sector })), definition.direction)) {
    const source = rows.find((row) => row.id === item.id)!; await prisma.normalizedFeatureSnapshot.upsert({ where: { companyId_asOfDate_featureKey_modelVersion: { companyId: source.companyId, asOfDate: asOf, featureKey: definition.key, modelVersion: MODEL_V0.version } }, update: { rawValue: item.value!, winsorizedValue: item.winsorizedValue, normalizedValue: item.normalizedValue, percentileRank: item.percentileRank, peerGroupType: item.peerGroupType, peerGroupValue: item.peerGroupValue, peerGroupSize: item.peerGroupSize, direction: definition.direction, normalizationVersion: MODEL_V0.normalizationVersion, calculatedAt: new Date() }, create: { companyId: source.companyId, asOfDate: asOf, featureKey: definition.key, modelVersion: MODEL_V0.version, rawValue: item.value!, winsorizedValue: item.winsorizedValue, normalizedValue: item.normalizedValue, percentileRank: item.percentileRank, peerGroupType: item.peerGroupType, peerGroupValue: item.peerGroupValue, peerGroupSize: item.peerGroupSize, direction: definition.direction, normalizationVersion: MODEL_V0.normalizationVersion, calculatedAt: new Date() } }); written++;
  }
  return { written, eligible: eligible.size };
}

export async function calculateFactors(asOf: Date, runId?: string) {
  const model = await prisma.factorModelVersion.findUniqueOrThrow({ where: { modelKey_version: { modelKey: MODEL_V0.modelKey, version: MODEL_V0.version } } }), universe = await prisma.investmentUniverse.findFirstOrThrow({ where: { active: true } }), eligibleIds = await eligibleCompanyIds(asOf, universe.id); const memberships = await prisma.universeMembership.findMany({ where: { universeId: universe.id, effectiveFrom: { lte: asOf }, OR: [{ effectiveTo: null }, { effectiveTo: { gt: asOf } }] }, include: { company: true } });
  const drafts: Array<{ company: typeof memberships[number]["company"]; scores: Record<string, number | null>; confidence: number; risk: number | null; liquidity: ReturnType<typeof calculateLiquidity>; contributions: unknown; effective: unknown; dataAsOf: Date; warnings: string[]; eligible: boolean }> = [];
  for (const { company } of memberships) try {
    const [normalized, features, bars, spyBars] = await Promise.all([prisma.normalizedFeatureSnapshot.findMany({ where: { companyId: company.id, asOfDate: asOf, modelVersion: MODEL_V0.version } }), prisma.featureSnapshot.findMany({ where: { companyId: company.id, asOfDate: asOf, modelVersion: MODEL_V0.version } }), latestBars(company.id, asOf), prisma.company.findUnique({ where: { ticker: "SPY" }, select: { id: true } }).then((spy) => spy ? latestBars(spy.id, asOf) : [])]);
    const outputs: Record<string, ReturnType<typeof scoreFactor>> = {};
    for (const factor of Object.keys(MODEL_V0.factorDefinitions) as Array<keyof typeof MODEL_V0.factorDefinitions>) { const definition = MODEL_V0.factorDefinitions[factor]; const contributions: Contribution[] = Object.entries(definition.featureWeights).map(([key, weight]) => { const normalizedValue = normalized.find((item) => item.featureKey === key), raw = features.find((item) => item.featureKey === key); return { featureKey: key, factor, percentile: number(normalizedValue?.percentileRank), weight, rawValue: number(raw?.value), dataAsOf: raw?.sourceAsOf?.toISOString(), peerGroup: normalizedValue ? `${normalizedValue.peerGroupType}:${normalizedValue.peerGroupValue ?? "ALL"}` : undefined, warnings: (raw?.warnings as string[] | null) ?? [] }; }); outputs[factor] = scoreFactor(contributions, definition.minimumCoverage); }
    const scores = Object.fromEntries(Object.entries(outputs).map(([key, output]) => [key, output.score])), alpha = aggregateAlpha(scores, Object.fromEntries(Object.entries(outputs).map(([key, output]) => [key, output.completeness]))), ohlcv = toOhlcv(bars), riskMetrics = calculateRisk(ohlcv, toOhlcv(spyBars)), risk = riskScoreFromMetrics(riskMetrics), liquidity = calculateLiquidity(ohlcv), featureCoverage = features.length ? features.filter((item) => item.value != null).length / features.length : 0, latestPrice = bars.at(-1)?.timestamp, latestFact = features.map((item) => item.sourceAvailableAt).filter((item): item is Date => item != null).sort((a, b) => b.getTime() - a.getTime())[0];
    const priceAge = latestPrice ? (asOf.getTime() - latestPrice.getTime()) / 864e5 : Infinity, factAge = latestFact ? (asOf.getTime() - latestFact.getTime()) / 864e5 : Infinity;
    const confidence = confidenceScore({ featureCompleteness: featureCoverage * 100, factorCompleteness: alpha.overallCoverage * 100, freshness: Math.max(0, 100 - Math.max(0, factAge - 90) / 3), providerConsistency: new Set(features.map((item) => item.provider).filter(Boolean)).size <= 1 ? 100 : 80, peerSample: Math.min(100, (normalized.reduce((sum, item) => sum + item.peerGroupSize, 0) / (normalized.length || 1)) * 5), filingFreshness: Math.max(0, 100 - Math.max(0, factAge - 90) / 3), priceFreshness: priceAge <= 3 ? 100 : priceAge <= 7 ? 70 : 25, classification: company.industry && company.sector ? 100 : 0, warningPenalty: features.filter((item) => item.warnings && JSON.stringify(item.warnings) !== "[]").length });
    drafts.push({ company, scores, confidence, risk, liquidity, contributions: Object.values(outputs).flatMap((output) => output.contributions), effective: { factors: alpha.effectiveWeights, features: Object.fromEntries(Object.entries(outputs).map(([key, output]) => [key, output.effectiveWeights])) }, dataAsOf: latestPrice ?? asOf, warnings: alpha.alphaScore == null ? ["INSUFFICIENT_MODEL_COVERAGE"] : [], eligible: eligibleIds.has(company.id) });
    await prisma.riskMetricSnapshot.upsert({ where: { companyId_asOfDate_modelVersion: { companyId: company.id, asOfDate: asOf, modelVersion: MODEL_V0.version } }, update: { ...riskMetrics, riskScore: risk, classification: riskClassification(risk), calculatedAt: new Date() }, create: { companyId: company.id, asOfDate: asOf, modelVersion: MODEL_V0.version, ...riskMetrics, riskScore: risk, classification: riskClassification(risk), calculatedAt: new Date() } });
    await prisma.liquiditySnapshot.upsert({ where: { companyId_asOfDate: { companyId: company.id, asOfDate: asOf } }, update: { ...liquidity, calculatedAt: new Date() }, create: { companyId: company.id, asOfDate: asOf, ...liquidity, calculatedAt: new Date() } });
  } catch (error) { if (runId) await prisma.modelCalculationFailure.create({ data: { runId, companyId: company.id, stage: "FACTOR", message: error instanceof Error ? error.message : String(error) } }); }
  const eligible = drafts.filter((draft) => draft.eligible && draft.liquidity.classification !== "INELIGIBLE" && draft.scores.quality != null && draft.scores.growth != null && draft.scores.value != null && draft.scores.momentum != null), sorted = [...eligible].sort((a, b) => aggregateAlpha(b.scores).alphaScore! - aggregateAlpha(a.scores).alphaScore! || b.confidence - a.confidence || a.company.ticker.localeCompare(b.company.ticker));
  let scored = 0; for (const draft of drafts) { const aggregated = aggregateAlpha(draft.scores), eligibleForRank = draft.eligible && draft.liquidity.classification !== "INELIGIBLE", alphaScore = eligibleForRank ? aggregated.alphaScore : null, percentile = !eligibleForRank || sorted.indexOf(draft) < 0 ? null : eligible.length <= 1 ? .5 : 1 - sorted.indexOf(draft) / (eligible.length - 1), rank = sorted.indexOf(draft) + 1, factors = Object.entries(draft.scores).map(([factor, score]) => ({ factor, score, weight: MODEL_V0.factorWeights[factor as keyof typeof MODEL_V0.factorWeights], contribution: score == null ? null : score * MODEL_V0.factorWeights[factor as keyof typeof MODEL_V0.factorWeights] })) as Prisma.InputJsonValue;
    await prisma.factorScoreSnapshot.upsert({ where: { companyId_asOfDate_modelVersionId: { companyId: draft.company.id, asOfDate: asOf, modelVersionId: model.id } }, update: { modelCalculationRunId: runId, qualityScore: draft.scores.quality, growthScore: draft.scores.growth, valueScore: draft.scores.value, momentumScore: draft.scores.momentum, alphaScore, confidenceScore: draft.confidence, riskScore: draft.risk, liquidityScore: draft.liquidity.liquidityScore, universePercentile: percentile, currentUniverseRank: rank || null, candidateBand: candidateBand(percentile, eligibleForRank, alphaScore != null), calculatedAt: new Date(), dataAsOf: draft.dataAsOf, priceAsOf: draft.dataAsOf, featureContributions: draft.contributions as Prisma.InputJsonValue, factorContributions: factors, effectiveWeights: draft.effective as Prisma.InputJsonValue, warnings: draft.warnings }, create: { companyId: draft.company.id, asOfDate: asOf, modelVersionId: model.id, modelCalculationRunId: runId, universeRuleVersion: MODEL_V0.universeRulesVersion, qualityScore: draft.scores.quality, growthScore: draft.scores.growth, valueScore: draft.scores.value, momentumScore: draft.scores.momentum, alphaScore, confidenceScore: draft.confidence, riskScore: draft.risk, liquidityScore: draft.liquidity.liquidityScore, universePercentile: percentile, currentUniverseRank: rank || null, candidateBand: candidateBand(percentile, eligibleForRank, alphaScore != null), calculatedAt: new Date(), dataAsOf: draft.dataAsOf, priceAsOf: draft.dataAsOf, featureContributions: draft.contributions as Prisma.InputJsonValue, factorContributions: factors, effectiveWeights: draft.effective as Prisma.InputJsonValue, warnings: draft.warnings, isMock: false } }); if (alphaScore != null) scored++;
  }
  return { eligible: eligible.length, scored, failed: memberships.length - drafts.length };
}

export async function runDailyModel(asOf = new Date()) { const model = await prisma.factorModelVersion.findUniqueOrThrow({ where: { modelKey_version: { modelKey: MODEL_V0.modelKey, version: MODEL_V0.version } } }), universe = await prisma.investmentUniverse.findFirstOrThrow({ where: { active: true } }), run = await prisma.modelCalculationRun.create({ data: { modelVersionId: model.id, universeId: universe.id, asOfDate: asOf, status: "RUNNING", startedAt: new Date() } }); try { const features = await calculateFeatures(asOf); const normalization = await normalizeFeatures(asOf); const scores = await calculateFactors(asOf, run.id); const status = features.failures.length || scores.failed ? "PARTIAL" : "COMPLETED"; return await prisma.modelCalculationRun.update({ where: { id: run.id }, data: { status, completedAt: new Date(), securitiesEligible: scores.eligible, securitiesScored: scores.scored, securitiesFailed: features.failures.length + scores.failed, errorSummary: features.failures.slice(0, 20).join("\n") || null, metadata: { featuresWritten: features.written, normalizedWritten: normalization.written } } }); } catch (error) { await prisma.modelCalculationRun.update({ where: { id: run.id }, data: { status: "FAILED", completedAt: new Date(), errorSummary: error instanceof Error ? error.message : String(error) } }); throw error; } }
