export type Ohlcv = { timestamp: Date; open: number; high: number; low: number; close: number; adjustedClose: number; volume: number | null };
const returns = (prices: number[]) => prices.slice(1).map((price, index) => price / prices[index] - 1);
const deviation = (values: number[]) => { if (values.length < 2) return null; const mean = values.reduce((sum, value) => sum + value, 0) / values.length; return Math.sqrt(values.reduce((sum, value) => sum + (value - mean) ** 2, 0) / (values.length - 1)); };
export const annualizedVolatility = (prices: number[]) => { const result = deviation(returns(prices)); return result == null ? null : result * Math.sqrt(252); };
export const maximumDrawdown = (prices: number[]) => { if (!prices.length) return null; let peak = prices[0], drawdown = 0; for (const price of prices) { peak = Math.max(peak, price); drawdown = Math.min(drawdown, price / peak - 1); } return drawdown; };
const covariance = (left: number[], right: number[]) => { const length = Math.min(left.length, right.length); if (length < 2) return null; const x = left.slice(-length), y = right.slice(-length), xMean = x.reduce((sum, value) => sum + value, 0) / length, yMean = y.reduce((sum, value) => sum + value, 0) / length; return x.reduce((sum, value, index) => sum + (value - xMean) * (y[index] - yMean), 0) / (length - 1); };

export function calculateRisk(bars: Ohlcv[], spyBars: Ohlcv[] = []) {
  const prices = bars.map((bar) => bar.adjustedClose), companyReturns = returns(prices), companyByDate = new Map(bars.map((bar) => [bar.timestamp.toISOString().slice(0, 10), bar.adjustedClose]));
  const alignedSpy = spyBars.filter((bar) => companyByDate.has(bar.timestamp.toISOString().slice(0, 10))), alignedCompanyPrices = alignedSpy.map((bar) => companyByDate.get(bar.timestamp.toISOString().slice(0, 10))!), spyReturns = returns(alignedSpy.map((bar) => bar.adjustedClose)), alignedCompanyReturns = returns(alignedCompanyPrices);
  const cov = covariance(alignedCompanyReturns, spyReturns), spyDeviation = deviation(spyReturns), companyDeviation = deviation(alignedCompanyReturns), downside = deviation(companyReturns.filter((value) => value < 0));
  const gaps = bars.slice(1).map((bar, index) => Math.abs(bar.open / bars[index].close - 1)), trueRanges = bars.slice(1).map((bar, index) => Math.max(bar.high - bar.low, Math.abs(bar.high - bars[index].close), Math.abs(bar.low - bars[index].close)) / bar.close);
  const correlation = cov == null || companyDeviation == null || spyDeviation == null || !companyDeviation || !spyDeviation ? null : cov / (companyDeviation * spyDeviation);
  return { volatility20d: annualizedVolatility(prices.slice(-21)), volatility60d: annualizedVolatility(prices.slice(-61)), volatility252d: annualizedVolatility(prices.slice(-253)), downsideVolatility: downside == null ? null : downside * Math.sqrt(252), betaSpy: cov != null && spyDeviation ? cov / (spyDeviation ** 2) : null, maximumDrawdown: maximumDrawdown(prices.slice(-252)), maximumDrawdown3y: prices.length >= 756 ? maximumDrawdown(prices.slice(-756)) : null, atrPercent: trueRanges.length >= 14 ? trueRanges.slice(-14).reduce((a, b) => a + b, 0) / 14 : null, largestOneDayGap: gaps.length ? Math.max(...gaps.slice(-252)) : null, recentGapFrequency: gaps.length ? gaps.slice(-63).filter((value) => value >= .05).length / Math.min(63, gaps.length) : null, correlationSpy: correlation, missingBarPercent: null };
}

export const riskScoreFromMetrics = (metrics: ReturnType<typeof calculateRisk>) => { const parts: Array<[number | null, number]> = [[metrics.volatility60d, .60], [metrics.maximumDrawdown == null ? null : Math.abs(metrics.maximumDrawdown), .20], [metrics.atrPercent, .10], [metrics.largestOneDayGap, .10]], used = parts.filter((item): item is [number, number] => item[0] != null); return used.length ? Math.min(100, used.reduce((sum, [value, weight]) => sum + Math.min(100, value * 200) * weight, 0) / used.reduce((sum, [, weight]) => sum + weight, 0)) : null; };
export function riskClassification(score: number | null) { if (score == null) return "INSUFFICIENT_DATA"; if (score < 25) return "LOW"; if (score < 50) return "MODERATE"; if (score < 75) return "HIGH"; return "VERY_HIGH"; }
