import { prisma } from "../lib/database/prisma";
import { getMarketDataProvider } from "../lib/data-providers/provider";
import { normalizePriceHistory } from "../lib/market/price-history";
import { mapWithConcurrency, runTrackedJob } from "../lib/jobs/runner";
import { SecEdgarProvider } from "../lib/providers/sec-provider";
import { financialFactRecordSchema } from "../lib/providers/schemas";
import { calculateFactors, calculateFeatures, normalizeFeatures, runDailyModel } from "../lib/research/engine";

const command = process.argv[2];
if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required");
if ((process.env.MARKET_DATA_PROVIDER ?? "").toLowerCase() === "mock" && (process.env.NODE_ENV === "production" || process.env.ALLOW_MOCK_DATA !== "true")) throw new Error("Mock ingestion is blocked. Configure a real provider; fixtures require explicit ALLOW_MOCK_DATA=true outside production.");

async function prices() {
  const provider = getMarketDataProvider();
  if (provider.constructor.name === "MockMarketDataProvider") throw new Error("Fixture price ingestion is not permitted by this command");
  const companies = await prisma.company.findMany({ where: { active: true }, select: { id: true, ticker: true } });
  return runTrackedJob("daily-prices", "yahoo-finance2-unofficial", async () => {
    const results = await mapWithConcurrency(companies, 3, async (company) => {
      console.log(`[prices] ${company.ticker}: downloading`);
      const [history, quote] = await Promise.all([provider.getPriceHistory(company.ticker, "1Y"), provider.getMarketSnapshot(company.ticker)]);
      const points = normalizePriceHistory(history); let written = 0;
      for (const point of points) {
        const open=point.open??point.price,high=point.high??point.price,low=point.low??point.price,close=point.close??point.price,adjusted=point.adjustedClose??point.price,volume=point.volume==null?null:BigInt(Math.trunc(point.volume));
        await prisma.priceBar.upsert({ where: { companyId_timestamp_interval_provider: { companyId: company.id, timestamp: new Date(point.timestamp), interval: "1d", provider: point.source } }, update: { open,high,low,close,adjustedClose:adjusted,volume,retrievedAt: new Date(point.retrievedAt), isMock: point.isMock }, create: { companyId: company.id, timestamp: new Date(point.timestamp), interval: "1d", open,high,low,close,adjustedClose:adjusted,volume,provider: point.source, retrievedAt: new Date(point.retrievedAt), effectiveAt: new Date(point.timestamp), isMock: point.isMock } }); written++;
      }
      await prisma.marketSnapshot.create({data:{companyId:company.id,timestamp:new Date(quote.retrievedAt),price:quote.currentPrice,previousClose:quote.previousClose,currentPrice:quote.currentPrice,dailyChangeAmount:quote.dailyChangeAmount,dailyChangePercent:quote.dailyChangePercent,marketStatus:quote.marketStatus,priceTimestamp:new Date(quote.priceTimestamp),marketCap:quote.marketCap,volume:quote.volume==null?null:BigInt(Math.trunc(quote.volume)),fiftyTwoWeekHigh:quote.fiftyTwoWeekHigh,fiftyTwoWeekLow:quote.fiftyTwoWeekLow,fiftyDayMovingAverage:quote.fiftyDayMovingAverage,twoHundredDayMovingAverage:quote.twoHundredDayMovingAverage,provider:quote.source,retrievedAt:new Date(quote.retrievedAt),effectiveAt:new Date(quote.priceTimestamp),isMock:quote.isMock}});
      console.log(`[prices] ${company.ticker}: stored ${written} bars`);
      return written;
    });
    const failures = results.flatMap((result, index) => result.status === "rejected" ? [`${companies[index].ticker}: ${result.reason instanceof Error ? result.reason.message : String(result.reason)}`] : []);
    return { recordsRead: companies.length, recordsWritten: results.reduce((sum, result) => sum + (result.status === "fulfilled" ? result.value : 0), 0), recordsFailed: failures.length, errors: failures };
  });
}

async function securityMaster() {
  const provider=getMarketDataProvider();
  if(provider.constructor.name==="MockMarketDataProvider")throw new Error("Fixture security-master ingestion is not permitted by this command");
  const companies=await prisma.company.findMany({where:{active:true},select:{id:true,ticker:true}});
  return runTrackedJob("security-master","configured-market-provider",async()=>{const results=await mapWithConcurrency(companies,3,async company=>{const profile=await provider.getCompanyProfile(company.ticker);await prisma.company.update({where:{id:company.id},data:{name:profile.name,sector:profile.sector,industry:profile.industry,description:profile.description,exchange:profile.exchange,country:profile.country,currency:profile.currency,securityType:profile.securityType}});return 1});const failures=results.flatMap((x,i)=>x.status==="rejected"?[`${companies[i].ticker}: ${x.reason instanceof Error?x.reason.message:String(x.reason)}`]:[]);return{recordsRead:companies.length,recordsWritten:results.filter(x=>x.status==="fulfilled").length,recordsFailed:failures.length,errors:failures}});
}

const calculationDate=()=>{const requested=process.argv[3];const value=requested?new Date(`${requested}T23:59:59.999Z`):new Date();if(Number.isNaN(value.getTime()))throw new Error("Calculation date must be YYYY-MM-DD");return value};
async function resolveCiks(){const companies=await prisma.company.findMany({where:{active:true},select:{id:true,ticker:true,cik:true}});if(companies.every(x=>x.cik))return;if(!process.env.SEC_USER_AGENT)throw new Error("SEC_USER_AGENT is required to resolve CIKs");const response=await fetch("https://www.sec.gov/files/company_tickers.json",{headers:{"User-Agent":process.env.SEC_USER_AGENT}});if(!response.ok)throw new Error(`SEC ticker map failed: ${response.status}`);const entries=Object.values(await response.json() as Record<string,{ticker:string;cik_str:number}>);const byTicker=new Map(entries.map(x=>[x.ticker.toUpperCase(),String(x.cik_str)]));for(const company of companies){const cik=company.cik??byTicker.get(company.ticker);if(cik)await prisma.company.update({where:{id:company.id},data:{cik}})}}
async function fundamentals(){const companies=await prisma.company.findMany({where:{active:true,cik:{not:null}},select:{id:true,ticker:true,cik:true}});const provider=new SecEdgarProvider(Object.fromEntries(companies.map(x=>[x.ticker,x.cik!])));return runTrackedJob("fundamentals","SEC_EDGAR",async()=>{const results=await mapWithConcurrency(companies,2,async company=>{const filings=await provider.getFilings(company.ticker);for(const filing of filings.filter(x=>["10-K","10-Q","20-F","40-F"].includes(x.formType)))await prisma.filing.upsert({where:{accessionNumber:filing.accessionNumber},update:{acceptedAt:filing.acceptedAt?new Date(filing.acceptedAt):null,retrievedAt:new Date(filing.retrievedAt)},create:{companyId:company.id,accessionNumber:filing.accessionNumber,formType:filing.formType,filingDate:new Date(filing.filingDate),periodEnd:filing.periodEnd?new Date(filing.periodEnd):null,acceptedAt:filing.acceptedAt?new Date(filing.acceptedAt):null,sourceUrl:filing.sourceUrl,provider:filing.provider,retrievedAt:new Date(filing.retrievedAt),isMock:false}});let count=0;for(const raw of await provider.getFinancialFacts(company.ticker)){const fact=financialFactRecordSchema.parse(raw);const filing=fact.accessionNumber?await prisma.filing.findUnique({where:{accessionNumber:fact.accessionNumber},select:{id:true}}):null;await prisma.financialFact.upsert({where:{companyId_metricKey_periodEnd_publishedAt_provider:{companyId:company.id,metricKey:fact.metricKey,periodEnd:new Date(fact.periodEnd),publishedAt:new Date(fact.publishedAt!),provider:fact.provider}},update:{value:fact.value,retrievedAt:new Date(fact.retrievedAt),filingId:filing?.id,isRestated:fact.isRestated},create:{companyId:company.id,filingId:filing?.id,metricKey:fact.metricKey,value:fact.value,unit:fact.unit,periodStart:fact.periodStart?new Date(fact.periodStart):null,periodEnd:new Date(fact.periodEnd),publishedAt:new Date(fact.publishedAt!),fiscalYear:fact.fiscalYear,fiscalQuarter:fact.fiscalQuarter,periodType:fact.periodType,provider:fact.provider,sourceIdentifier:fact.sourceIdentifier,retrievedAt:new Date(fact.retrievedAt),isRestated:fact.isRestated,isMock:false}});count++;}return count});const failures=results.flatMap((x,i)=>x.status==="rejected"?[`${companies[i].ticker}: ${String(x.reason)}`]:[]);return{recordsRead:companies.length,recordsWritten:results.reduce((s,x)=>s+(x.status==="fulfilled"?x.value:0),0),recordsFailed:failures.length,errors:failures}})}
async function fundamentalsFast(){const companies=await prisma.company.findMany({where:{active:true,cik:{not:null}},select:{id:true,ticker:true,cik:true}});const provider=new SecEdgarProvider(Object.fromEntries(companies.map(x=>[x.ticker,x.cik!])));return runTrackedJob("fundamentals","SEC_EDGAR",async()=>{const results=await mapWithConcurrency(companies,2,async company=>{console.log(`[fundamentals] ${company.ticker}: downloading`);const [filings,rawFacts]=await Promise.all([provider.getFilings(company.ticker),provider.getFinancialFacts(company.ticker)]);const accepted=filings.filter(x=>["10-K","10-Q","20-F","40-F"].includes(x.formType));await prisma.filing.createMany({data:accepted.map(x=>({companyId:company.id,accessionNumber:x.accessionNumber,formType:x.formType,filingDate:new Date(x.filingDate),periodEnd:x.periodEnd?new Date(x.periodEnd):null,acceptedAt:x.acceptedAt?new Date(x.acceptedAt):null,sourceUrl:x.sourceUrl,provider:x.provider,retrievedAt:new Date(x.retrievedAt),isMock:false})),skipDuplicates:true});const facts=rawFacts.map(x=>financialFactRecordSchema.parse(x));await prisma.financialFact.createMany({data:facts.map(x=>({companyId:company.id,metricKey:x.metricKey,value:x.value,unit:x.unit,periodStart:x.periodStart?new Date(x.periodStart):null,periodEnd:new Date(x.periodEnd),publishedAt:new Date(x.publishedAt!),fiscalYear:x.fiscalYear,fiscalQuarter:x.fiscalQuarter,periodType:x.periodType,provider:x.provider,sourceIdentifier:x.sourceIdentifier,retrievedAt:new Date(x.retrievedAt),isRestated:x.isRestated,isMock:false})),skipDuplicates:true});console.log(`[fundamentals] ${company.ticker}: stored ${facts.length} facts`);return facts.length});const failures=results.flatMap((x,i)=>x.status==="rejected"?[`${companies[i].ticker}: ${x.reason instanceof Error?x.reason.message:String(x.reason)}`]:[]);return{recordsRead:companies.length,recordsWritten:results.reduce((s,x)=>s+(x.status==="fulfilled"?x.value:0),0),recordsFailed:failures.length,errors:failures}})}
async function main(){if(command==="security-master")console.log(await securityMaster());else if(command==="prices")console.log(await prices());else if(command==="fundamentals")console.log(await fundamentalsFast());else if(command==="features")console.log(await calculateFeatures(calculationDate()));else if(command==="normalize")console.log(await normalizeFeatures(calculationDate()));else if(command==="factors")console.log(await calculateFactors(calculationDate()));else if(command==="daily")console.log(await runDailyModel(calculationDate()));else throw new Error("Use security-master, prices, fundamentals, features, normalize, factors, or daily")}
(command==="fundamentals"?resolveCiks():Promise.resolve()).then(main).finally(() => prisma.$disconnect());
